require 'rubygems'
require 'bundler/setup'
require 'zip'

require 'powerpointer/version'
require 'powerpointer/globals'
require 'powerpointer/shape'
require 'powerpointer/export_file'
require 'powerpointer/relationships'
require 'powerpointer/content_types'
require 'powerpointer/slide'
require 'powerpointer/presentation'
require 'powerpointer/presentation_package'
require 'powerpointer/content_types/default'
require 'powerpointer/content_types/override'
